#ifndef SL_COMPONENT_CATALOG_H
#define SL_COMPONENT_CATALOG_H


#define SL_CATALOG_TFLITE_MICRO_PRESENT

// #define SL_CATALOG_IOSTREAM_UART_COMMON_PRESENT
// #define SL_CATALOG_MVP_PRESENT
// #define SL_CATALOG_MX25_FLASH_SHUTDOWN_EUSART_PRESENT
// #define SL_CATALOG_POWER_MANAGER_PRESENT
// #define SL_CATALOG_PRINTF_PRESENT
// #define SL_CATALOG_BTN0_PRESENT
// #define SL_CATALOG_SIMPLE_BUTTON_PRESENT
// #define SL_CATALOG_SIMPLE_BUTTON_BTN0_PRESENT
// #define SL_CATALOG_BTN1_PRESENT
// #define SL_CATALOG_SIMPLE_BUTTON_BTN1_PRESENT
// #define SL_CATALOG_LED0_PRESENT
// #define SL_CATALOG_SIMPLE_LED_PRESENT
// #define SL_CATALOG_SIMPLE_LED_LED0_PRESENT
// #define SL_CATALOG_LED1_PRESENT
// #define SL_CATALOG_SIMPLE_LED_LED1_PRESENT
//
// #define SL_CATALOG_TFLITE_MICRO_PRESENT

#endif // SL_COMPONENT_CATALOG_H
