# automatically generated by the FlatBuffers compiler, do not modify

# namespace: 

import flatbuffers
from flatbuffers.compat import import_numpy
np = import_numpy()

class BoolValue(object):
    __slots__ = ['_tab']

    @classmethod
    def GetRootAs(cls, buf, offset=0):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, offset)
        x = BoolValue()
        x.Init(buf, n + offset)
        return x

    @classmethod
    def GetRootAsBoolValue(cls, buf, offset=0):
        """This method is deprecated. Please switch to GetRootAs."""
        return cls.GetRootAs(buf, offset)
    # BoolValue
    def Init(self, buf, pos):
        self._tab = flatbuffers.table.Table(buf, pos)

    # BoolValue
    def Value(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            return bool(self._tab.Get(flatbuffers.number_types.BoolFlags, o + self._tab.Pos))
        return False

def BoolValueStart(builder):
    builder.StartObject(1)

def Start(builder):
    BoolValueStart(builder)

def BoolValueAddValue(builder, value):
    builder.PrependBoolSlot(0, value, 0)

def AddValue(builder, value):
    BoolValueAddValue(builder, value)

def BoolValueEnd(builder):
    return builder.EndObject()

def End(builder):
    return BoolValueEnd(builder)
