# automatically generated by the FlatBuffers compiler, do not modify

# namespace: 

import flatbuffers
from flatbuffers.compat import import_numpy
np = import_numpy()

class Int16Value(object):
    __slots__ = ['_tab']

    @classmethod
    def GetRootAs(cls, buf, offset=0):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, offset)
        x = Int16Value()
        x.Init(buf, n + offset)
        return x

    @classmethod
    def GetRootAsInt16Value(cls, buf, offset=0):
        """This method is deprecated. Please switch to GetRootAs."""
        return cls.GetRootAs(buf, offset)
    # Int16Value
    def Init(self, buf, pos):
        self._tab = flatbuffers.table.Table(buf, pos)

    # Int16Value
    def Value(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Int16Flags, o + self._tab.Pos)
        return 0

def Int16ValueStart(builder):
    builder.StartObject(1)

def Start(builder):
    Int16ValueStart(builder)

def Int16ValueAddValue(builder, value):
    builder.PrependInt16Slot(0, value, 0)

def AddValue(builder, value):
    Int16ValueAddValue(builder, value)

def Int16ValueEnd(builder):
    return builder.EndObject()

def End(builder):
    return Int16ValueEnd(builder)
