# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: download_run.proto
# Protobuf Python Version: 4.25.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x12\x64ownload_run.proto\"\xb4\x03\n\x07Request\x12\x12\n\nimage_data\x18\x01 \x01(\x0c\x12\x12\n\nimage_path\x18\x02 \x01(\t\x12\x10\n\x08platform\x18\x03 \x01(\t\x12\x11\n\tmasserase\x18\x04 \x01(\x08\x12\x0e\n\x06\x64\x65vice\x18\x05 \x01(\t\x12\x15\n\rserial_number\x18\x06 \x01(\t\x12\x12\n\nip_address\x18\x07 \x01(\t\x12\x19\n\x11setup_script_data\x18\x08 \x01(\x0c\x12\x19\n\x11setup_script_args\x18\t \x01(\t\x12\x1b\n\x13program_script_data\x18\n \x01(\x0c\x12\x1b\n\x13program_script_args\x18\x0b \x01(\t\x12\x19\n\x11reset_script_data\x18\x0c \x01(\x0c\x12\x19\n\x11reset_script_args\x18\r \x01(\t\x12\x0c\n\x04port\x18\x0e \x01(\t\x12\x0c\n\x04\x62\x61ud\x18\x0f \x01(\x05\x12\x0f\n\x07timeout\x18\x10 \x01(\x02\x12\x11\n\tstart_msg\x18\x11 \x01(\t\x12\x14\n\x0c\x63omplete_msg\x18\x12 \x01(\t\x12\x0f\n\x07retries\x18\x13 \x01(\x05\x12\x14\n\x0clock_timeout\x18\x14 \x01(\x02\"4\n\x08Response\x12\x17\n\x06status\x18\x01 \x01(\x0e\x32\x07.Status\x12\x0f\n\x07message\x18\x02 \x01(\t*a\n\x06Status\x12\x0b\n\x07Timeout\x10\x00\x12\x0b\n\x07Running\x10\x01\x12\x0c\n\x08\x43omplete\x10\x02\x12\t\n\x05\x45rror\x10\x03\x12\x0c\n\x08\x44\x65\x62ugLog\x10\x04\x12\x07\n\x03Log\x10\x05\x12\r\n\tSerialOut\x10\x06\x32\x36\n\x0b\x44ownloadRun\x12\'\n\x0e\x44ownloadAndRun\x12\x08.Request\x1a\t.Response0\x01\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'download_run_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  DESCRIPTOR._options = None
  _globals['_STATUS']._serialized_start=515
  _globals['_STATUS']._serialized_end=612
  _globals['_REQUEST']._serialized_start=23
  _globals['_REQUEST']._serialized_end=459
  _globals['_RESPONSE']._serialized_start=461
  _globals['_RESPONSE']._serialized_end=513
  _globals['_DOWNLOADRUN']._serialized_start=614
  _globals['_DOWNLOADRUN']._serialized_end=668
# @@protoc_insertion_point(module_scope)
